apiVersion: v2
name: pagopa-gpd-upload-function
description: Microservice description
type: application
version: 0.104.0
appVersion: 0.1.4
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
