apiVersion: v2
name: pagopa-gpd-upload-function
description: Microservice description
type: application
version: 0.99.0
appVersion: 0.1.0
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
