apiVersion: v2
name: pagopa-gpd-upload-function
description: Microservice description
type: application
version: 0.115.0
appVersion: 0.5.1
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
