apiVersion: v2
name: pagopa-gpd-upload-function
description: Microservice description
type: application
version: 0.111.0
appVersion: 0.3.0-1-PAGOPA-3305-report-segregation-by-servicetype
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
