apiVersion: v2
name: pagopa-gpd-upload-function
description: Microservice description
type: application
version: 0.39.0
appVersion: 0.0.6-1-PAGOPA-1449
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
