microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-gpd-upload-function
    tag: "0.0.15-2-PAGOPA-1787-cosmos-operation-refactoring"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weudev.gps.internal.dev.platform.pagopa.it"
    path: /pagopa-gpd-upload-function/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1Gi"
      cpu: "0.5"
    limits:
      memory: "1Gi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  fileConfig: {}
  envConfig:
    WEBSITE_SITE_NAME: "pagopagpduploadfunction" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    GPD_HOST: "https://api.dev.platform.pagopa.it/gpd/api"
    RETRY_MAX_ATTEMPTS: "1"
    RETRY_MAX_DELAY: "10000"
    BLOCK_SIZE: "10"
    COSMOS_URI: "https://pagopa-d-weu-gps-cosmos-account.documents.azure.com:443/"
    GPD_DB_NAME: "gpd_db"
    GPD_CONTAINER_NAME: "gpd_upload_status"
    BLOB_EVENTS_QUEUE: "gpd-blob-events-queue"
    VALID_POSITIONS_QUEUE: "gpd-valid-debt-position-queue"
    CHUNK_SIZE: "50"
    MAX_RETRY: "1"
    RETRY_DELAY_IN_SECONDS: "300"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    AzureWebJobsStorage: 'gpd-upload-sa-connection-string'
    GPD_SA_CONNECTION_STRING: 'gpd-upload-sa-connection-string'
    GPD_SUBSCRIPTION_KEY: 'gpd-core-key-for-gpd-upload'
    COSMOS_KEY: 'gpd-upload-db-key'
  keyvault:
    name: "pagopa-d-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - "user"
  canaryDelivery:
    create: false
    deployment:
      create: false
      image:
        tag: 0.5.6
  create: false
